name: "Build"
description: "Builds a package and runs unit tests without pushing"

inputs:
  dotnet_version:
    description: "Version of dotnet to use for testing"
    required: true
  solution_path:
    description: "Path to solution to build e.g. src/Libraries.sln"
    required: true
  github_token:
    description: "Token used to access github for uploading coverage report"
    required: true

runs:
  using: "composite"
  steps:
    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: ${{ inputs.dotnet_version }}
    - name: Build and run unit tests
      shell: bash
      run: |
        dotnet build ${{ inputs.solution_path }} --no-restore
        dotnet test ${{ inputs.solution_path }} --no-build -v=normal /p:CollectCoverage=true /p:CoverletOutput=TestResults/coverage.json /p:CoverletOutputFormat=lcov /p:Threshold=70
    - name: Publish coverage report to coveralls.io
      uses: coverallsapp/github-action@master
      with:
        github-token: ${{ inputs.GITHUB_TOKEN }}
        path-to-lcov: TestResults/coverage.json

      




