name: "Build for PRe"
description: "Builds a solution and runs unit tests without pushing"

inputs:
  dotnet_version:
    description: "Version of dotnet to use for testing"
    required: true
  solution_path:
    description: "Path to solution to build, e.g. src/Libraries.sln"
    required: true
  github_token:
    description: "Token used to access github for uploading coverage report"
    required: true

runs:
  using: "composite"
  steps:
    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: ${{ inputs.dotnet_version }}
    - name: Restore .NET
      shell: bash
      run: dotnet restore ${{ inputs.solution_path }}
    - name: Build and run unit tests
      shell: bash
      run: |
        dotnet build ${{ inputs.solution_path }} --no-restore
        dotnet test ${{ inputs.solution_path }} --no-build -v=normal /p:CollectCoverage=true /p:CoverletOutput=TestResults/coverage.json /p:CoverletOutputFormat=lcov /p:Threshold=70
    - name: Publish coverage report to coveralls.io
      uses: coverallsapp/github-action@master
      with:
        github-token: ${{ inputs.GITHUB_TOKEN }}
        path-to-lcov: TestResults/coverage.json
    - name: Include coverage report in PRe
      uses: romeovs/lcov-reporter-action@v0.2.16
      with:
        github-token: ${{ inputs.GITHUB_TOKEN }}     
        lcov-file: ${{ inputs.tests_path }}/TestResults/coverage.json
      




