name: Helpm8-ci

on:
  push:
    branches: [ "main", "feature/*" ]
  # pull_request:
  #   branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        fetch-depth: 0    
    - name: Install GitVersion
      uses: gittools/actions/gitversion/setup@v0.9.7
      with:
        versionSpec: '5.x'        
    - name: Determine Version
      id: gitversion
      uses: gittools/actions/gitversion/execute@v0.9.7
      with:
        useConfigFile: true
        configFilePath: ./.github/GitVersion.yml
        updateAssembyInfo: true
    - name: Display SemVer
      run: |
        echo "SemVer: $GITVERSION_SEMVER"        
    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 3.1.x
    - name: Restore dependencies
      run: dotnet restore ./src/Helpm8.sln
    - name: Build
      run: |
        dotnet build ./src/Helpm8.sln --no-restore --configuration Release /p:Version=${{ 
          steps.gitversion.outputs.AssemblySemVer }} /p:AssemblyVersion=${{
          steps.gitversion.outputs.AssemblySemVer }} /p:InformationalVersion=${{
          steps.gitversion.outputs.InformationalVersion }} 
    - name: Test
      run: | 
        dotnet test ./src/Helpm8.sln --no-build --verbosity normal --configuration Release --logger trx --results-directory "TestResults" /p:Version=${{
          steps.gitversion.outputs.AssemblySemVer }}
    - name: Upload dotnet test results
      uses: actions/upload-artifact@v3
      with:
        name: dotnet-results
        path: TestResults
      # Use always() to always run this step to publish test results when there are test failures
      if: ${{ always() }}      
    - name: Package nuget
      run: dotnet pack ./src/Helpm8.sln --no-build --configuration Release -o:package /p:PackageVersion=${{ steps.gitversion.outputs.NuGetVersion }}
    - name: Push nuget to GitHub
      run: dotnet nuget push ./package/*.nupkg --source https://nuget.pkg.github.com/wiesenwischer/index.json --api-key ${{ secrets.GITHUB_TOKEN }}

    - name: Report test results
      uses: zyborg/dotnet-tests-report@v1
      with:
        project_path: Helpm8.Core.Tests
        report_name: Helpm8.Core_tests
        report_title: Helpm8.Core Tests
        github_token: ${{ secrets.GITHUB_TOKEN }}
        gist_name: Helpm8.Core_tests.md
        gist_badge_label: 'Helpm8.Core: %Counters_passed%/%Counters_total%'
        gist_token: ${{ secrets.GIST_TOKEN }}

