name: .NET

on:
  push:
    branches: [ "feature/gitversion" ]
  pull_request:
    branches: [ "feature/gitversion" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        fetch-depth: 0    
    - name: Install GitVersion
      uses: gittools/actions/gitversion/setup@v0.9.7
      with:
        versionSpec: '5.x'        
    - name: Determine Version
      uses: gittools/actions/gitversion/execute@v0.9.7
    - name: Display SemVer
      run: |
        echo "SemVer: $GITVERSION_SEMVER"        
    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 3.1.x
    - name: Restore dependencies
      run: dotnet restore ./src/Helpm8.sln
    - name: Build
      run: dotnet build ./src/Helpm8.sln --no-restore --configuration Release
    - name: Test
      run: dotnet test ./src/Helpm8.sln --no-build --verbosity normal --configuration Release --logger trx --results-directory "TestResults"
    - name: Upload dotnet test results
      uses: actions/upload-artifact@v3
      with:
        name: dotnet-results
        path: TestResults
      # Use always() to always run this step to publish test results when there are test failures
      if: ${{ always() }}      
