name: .NET

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 5.0.x
    - name: Restore dependencies
      run: dotnet restore ./src/Help8m.sln
    - name: Build
      run: dotnet build ./src/Help8m.sln --no-restore --configuration Realease
    - name: Test
      run: dotnet test --no-build --verbosity normal
