name: Libraries

on:
  workflow_dispatch:
  push:
    branches:
      - main
      - file-provider

    paths:
      - src/libraries/**
      - .github/workflows/libraries.yml
      - .github/workflows/composite/**

  pull_request:
    branches:
      - main

    paths:
      - src/libraries/**
      - .github/workflows/libraries.yml
      - .github/workflows/composite/**

jobs:

  BuildForPR:
    runs-on: ubuntu-latest
    if: ${{ github.event_name == 'pull_request' }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - uses: ./.github/workflows/composite/build-test-pr
        with:
          dotnet_version: 3.1.x
          solution_path: src/Libraries.sln
          github_token: ${{ secrets.GITHUB_TOKEN }}          

  Build:
    runs-on: ubuntu-latest
    if: ${{ github.event_name != 'pull_request'}}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - uses: ./.github/workflows/composite/build-test
        with:
          dotnet_version: 3.1.x
          solution_path: src/Libraries.sln
          github_token: ${{ secrets.GITHUB_TOKEN }}