name: Tests and coverage

on:
  # Manual trigger from the UI
  workflow_dispatch:
    inputs:
      message:
        description: 'Run tests and publish code coverage'

  # Dependency to a forking workflow
  workflow_run:
    workflows: ["Core CI"]
    type:
      - complete
  
env:
  DOTNET_NOLOGO: true

jobs:
  build:
    name: ${{ matrix.name }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: windows-latest
            name: Windows
      fail-fast: false
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Setup .NET
        uses: actions/setup-dotnet@v2
        with: 
          dotnet-version: |
            3.1.x
            6.x      
      - name: Run tests with coverage
        if: matrix.name == 'Windows'
        run: dotnet test src/libraries/Helpm8.Core.Tests --configuration Release -v=normal /p:CollectCoverage=true /p:CoverletOutput=../../../TestResults/Helpm8.Core.info /p:CoverletOutputFormat=lcov
      - name: Publish coverage report to coveralls.io
        if: matrix.name == 'Windows'
        uses: coverallsapp/github-action@master
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          path-to-lcov: TestResults/Helpm8.Core.info
          